import Head from "next/head";
import { useContext, useState, useEffect } from "react";
import { AppContext } from "../context/AppContext";
import HomePage from "../components/home/HomePage";

export default function Home() {
  const [currentTheme, setCurrentTheme] = useState("");
  const data = useContext(AppContext);

  useEffect(() => {
    const theme = data.theme === "light" ? "bg" : "bg-dark";
    setCurrentTheme(theme);
  }, []);

  return (
    <div className={`${currentTheme} bg-gray-800 min-h-[100vh] w-[100%] lg:pl-[150px]`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </div>
  );
}
